apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookinfo
resources:
- deployment.yaml
- ingress.yaml
- clusterbind.yaml
- service-account.yaml
configMapGenerator:
- name: example-configmap-1
  files:
  - config.property
