apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: instavote
    tier: fe
  name: instavote
spec:
  replicas: 6
  template:
    spec:
      containers:
      - image: schoolofdevops/vote:v1
        name: vote
