apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: instavote
  name: instavote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instavote
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: instavote
    spec:
      containers:
      - command:
        - sleep
        - "5000"
        image: schoolofdevops/vote:v4
        name: vote
        resources: {}
status: {}
