apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: instavote
    tier: fe
  name: instavote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instavote
  strategy: {}
  template:
    metadata:
      labels:
        app: instavote
        tier: fe
    spec:
      containers:
      - image: schoolofdevops/vote:v4
        name: vote
        resources: {}
status: {}
